<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>json</string>
	</array>
	<key>name</key>
	<string>JSON</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#json</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arrays</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>meta.structure.array.json</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#json</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.array.json</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\s\]]</string>
							<key>name</key>
							<string>invalid.character.json</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>/\*.*?\*/</string>
					<key>name</key>
					<string>comment.block.json</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.json</string>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.json</string>
				</dict>
			</array>
		</dict>
		<key>json</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers-and-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>meta</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>("name")\s*(:)\s(?=")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.key-value.json</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.name.json</string>
					<key>end</key>
					<string>(?&lt;=")\s*(,)?</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.json</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers-and-constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?</string>
					<key>name</key>
					<string>constant.numeric.json</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.json</string>
				</dict>
			</array>
		</dict>
		<key>objects</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.structure.dictionary.json</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#meta</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>:</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.dictionary.key-value.json</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(,)|(?=\})</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.dictionary.json</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#json</string>
								</dict>
								<dict>
									<key>match</key>
									<string>[^\s,]</string>
									<key>name</key>
									<string>invalid.character.json</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\s\}]</string>
							<key>name</key>
							<string>invalid.character.json</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"|\n</string>
					<key>name</key>
					<string>string.quoted.double.json</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[^"](?=\n)</string>
							<key>name</key>
							<string>invalid.string.json</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})</string>
							<key>name</key>
							<string>constant.character.escape.json</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.character.escape.json</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.json</string>
</dict>
</plist>
