<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Maven Build Output</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.indicator.error.maven</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.indicator.warning.maven</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.file.maven</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.maven</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.maven</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.maven</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?:(\[ERROR\])|(\[WARNING\])) (.+):\[(\d+),(\d+)\] (.*)</string>
			<key>name</key>
			<string>meta.compile.error.maven</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\[ERROR\]) (Failed to execute goal .*?: )(.*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.indicator.error.maven</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.result.maven</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.maven</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!x)x</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.indicator.info.maven</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.result.maven</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\[\w+\]) ([A-Z 0-9]{2,}\s)?(.*)</string>
					<key>name</key>
					<string>comment.maven</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#maven</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(junit\.framework\.\w+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.exception.maven</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^\s+at\b)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.junit.maven</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(expected|but was):</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.maven</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.exception.maven</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.maven</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?:Caused by: )?([\w\.]+(?:Exception|Failure|Error))(?:: (.*))?</string>
			<key>name</key>
			<string>meta.exception.maven</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.file.maven</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.maven</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*at [\w\.\$&lt;&gt;]+\((.*):(.*)\)</string>
			<key>name</key>
			<string>meta.exception.maven</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=Tests run:)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.maven</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.maven</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(Tests run|Failures|Errors|Skipped|Time elapsed): (\d+(?:[,.]\d+)*(?: sec)?)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#maven</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>maven</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.indicator.error.maven</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.indicator.warning.maven</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.indicator.info.maven</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.result.maven</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?:(\[ERROR\])|(\[WARNING\])|(\[INFO\]))\s+(\b[A-Z][A-Z 0-9]+\b)?(.*)</string>
					<key>name</key>
					<string>comment.maven</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.maven</string>
	<key>uuid</key>
	<string>B5F3B290-2625-11E4-8C21-0800200C9A66</string>
</dict>
</plist>
