<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xml</string>
	</array>
	<key>name</key>
	<string>XML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)\s*([-.\w]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\?&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.preprocessor.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-attribute</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;!DOCTYPE.+mybatis\.org//DTD Mapper 3\.0//EN)</string>
			<key>end</key>
			<string>^(?!x)x</string>
			<key>name</key>
			<string>source.mybatis</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doctype</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mybatis</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;project\s+xmlns=.http://maven\.apache\.org/POM)</string>
			<key>end</key>
			<string>^(?!x)x</string>
			<key>name</key>
			<string>source.maven</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doctype</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#maven</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#doctype</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;[-.\w]+)</string>
			<key>end</key>
			<string>^(?!x)x</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;[!#%]--</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.xml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>--&gt;</string>
					<key>name</key>
					<string>comment.block.xml</string>
				</dict>
			</array>
		</dict>
		<key>doctype</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;!)(DOCTYPE)\s+([-.\w]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.doctype.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.documentroot.xml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>name</key>
					<string>meta.tag.sgml.doctype.xml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>end</key>
							<string>\]</string>
							<key>name</key>
							<string>meta.internal-subset.xml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(&lt;!)(ENTITY)\s+(%)?\s*([:a-zA-Z_][:\w.-]*)(?:\s+(SYSTEM|PUBLIC)\s+)?</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.tag.xml</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.entity.xml</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.entity.xml</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>variable.entity.xml</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>keyword.entity-type.xml</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(&gt;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#quoted-strings</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.constant.xml</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>constant.character.parameter-entity.xml</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.constant.xml</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(%)([:a-zA-Z_][:\w.-]*)(;)</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#quoted-strings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>entity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.xml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)(?:[:a-zA-Z_][:\w.-]*|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.xml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[&amp;&lt;&gt;]</string>
					<key>name</key>
					<string>invalid.illegal.entity.xml</string>
				</dict>
			</array>
		</dict>
		<key>maven</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$\{.*?\}</string>
					<key>name</key>
					<string>constant.maven</string>
				</dict>
			</array>
		</dict>
		<key>mybatis</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=&lt;(select|update|insert|delete)\s+)</string>
					<key>contentName</key>
					<string>source.sql.mybatis</string>
					<key>end</key>
					<string>(?=&lt;/\1&gt;)</string>
					<key>name</key>
					<string>meta.mapping.mybatis</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;)((?:([-.\w]+)(:))?([-.\w]+))</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.xml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.xml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.namespace.xml</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.namespace.xml</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.localname.xml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/?&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.xml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.xml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.attribute.xml</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.attribute.xml</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.xml</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>entity.name.function.mybatis</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.xml</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(id)(=)(['"])(.+?)(\3)</string>
									<key>name</key>
									<string>meta.attribute.xml.mybatis</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#tag-attribute</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entity</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>[#$]\{</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.mybatis</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.other.mybatis</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.mybatis</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>variable.parameter.mybatis</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(?:\s*(javaType|jdbcType|mode)\s*(=))?\s*([.\w]+)</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>quoted-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(['"])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.xml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\1</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.xml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#entity</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)((?:([-.\w]+)(:))?([-.\w]+))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.namespace.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>/?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.xml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attribute</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.namespace.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.xml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;/)((?:([-.\w]+)(:))?([-.\w]+))\s*(&gt;)</string>
					<key>name</key>
					<string>meta.tag.xml</string>
				</dict>
			</array>
		</dict>
		<key>tag-attribute</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>((?:([-.\w]+)(:))?([-.\w]+))(=)(['"])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.attribute.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.attribute.namespace.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.attribute.localname.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.attribute.xml</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.xml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.attribute.xml</string>
					<key>end</key>
					<string>\6</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.attribute.xml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#entity</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>xml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!\[CDATA\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.cdata.begin.xml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.cdata.xml</string>
					<key>end</key>
					<string>]]&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.cdata.end.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.cdata.xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.xml</string>
	<key>uuid</key>
	<string>D3C4E6DA-6B1C-11D9-8CC2-000D93589AF6</string>
</dict>
</plist>
