<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>markdown</string>
		<string>md</string>
	</array>
	<key>name</key>
	<string>GitHub Markdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(`+)([^`]+?)\1</string>
			<key>name</key>
			<string>markup.raw.inline.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b__.+?__\b</string>
			<key>name</key>
			<string>markup.bold.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b_.+?_\b</string>
			<key>name</key>
			<string>markup.italic.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*.+?\*\*</string>
			<key>name</key>
			<string>markup.bold.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*.+?\*</string>
			<key>name</key>
			<string>markup.italic.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~~\S.+?\S~~</string>
			<key>name</key>
			<string>markup.strikethrough.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;.+?&gt;</string>
			<key>name</key>
			<string>markup.underline.link.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\[-`*_#+.!(){}\[\]\\&gt;]</string>
			<key>name</key>
			<string>constant.character.escape.markdown</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^#{1,6}(?!#)\s*(.*?)\s*#*$</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^([ ]{4}|\t).*$</string>
			<key>name</key>
			<string>markup.raw.block.markdown</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(```)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(```)$</string>
			<key>name</key>
			<string>markup.raw.block.fenced.markdown</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(```)(foobar2000)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.fenced.language.marker.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.foobar2000</string>
			<key>end</key>
			<string>^(```)$</string>
			<key>name</key>
			<string>markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.foobar2000</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.markdown</string>
	<key>uuid</key>
	<string>33E9E501-9B2C-4B8E-912D-79A43B839BDE</string>
</dict>
</plist>
