from snippets import Icon, generate

generate(
    "source.c",
    snippets={
        "pl": "printf($SEL0);",
        "dc": ("doc comment", r"/**-->${SELECTION/^\s*/ * /mg}$0--> */"),
        "main": ("main", "int main(${1:int argc, char* argv[]}) {}"),
        "fn": ("function", "${1:void} ${2:run}($3) {}"),
        ";;": (
            "i = 0; i < imax; i++",
            "${1:size_t} ${2:i} = 0; $2 < ${3:imax}; ${4:++$2}",
        ),
        "inc": ("#include <header>", "#include <$SEL0>"),
        "inq": ('#include "header"', '#include "$SEL0"'),
        "ifd": ("#if defined ... #endif", "#if defined($1)<->#endif"),
        "td": ("TODO", "// TODO: "),
    },
    completions={
        ("Keyword", Icon.KEYWORD): [
            "break",
            "continue",
            "enum",
            "goto",
            "return",
            "typedef",
        ],
        ("Modifier", Icon.MODIFIER): [
            "const",
            "static",
            "thread_local",
            "unsigned",
            "volatile",
        ],
        ("Function", Icon.FUNCTION): [
            "free",
            "malloc",
            "sizeof",
        ],
        ("Block", Icon.BLOCK): [
            "else {}",
            "for ($1) {}",
            "if ($1) {}",
            "struct $1 {};",
            "switch ($1) {}",
            "while ($1) {}",
        ],
        ("Macros", Icon.META): [
            "define",
            "elif",
            "endif",
            "error",
            "ifdef",
            "ifndef",
            "include",
            "pragma",
        ],
        ("Type", Icon.PRIMITIVE_TYPE): [
            "bool",
            "char",
            "double",
            "float",
            "int",
            "int16_t",
            "int32_t",
            "int64_t",
            "int8_t",
            "long",
            "size_t",
            "uint16_t",
            "uint32_t",
            "uint64_t",
            "uint8_t",
            "void",
        ],
        ("Constant", Icon.CONSTANT): [
            "false",
            "NULL",
            "true",
        ],
    },
)
