# [PackageDev] target_format: plist, ext: tmPreferences
scope: source.xml
settings:
  increaseIndentPattern: '^.*<(?![?!])[^\/]+>\s*$'
  decreaseIndentPattern: '^\s*<\/.*>\s*$'
  bracketIndentNextLinePattern: '^.*<[^>]+\s*$'
  icon: file_type_xml
  shellVariables:
  - name: TM_COMMENT_START
    value: '<!-- '
  - name: TM_COMMENT_END
    value: ' -->'
