<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sql</string>
	</array>
	<key>name</key>
	<string>SQL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(null|true|false)\b</string>
			<key>name</key>
			<string>constant.language.sql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.modifier.sql</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(create(?:\s+or\s+replace)|alter|drop)\s+(type)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.modifier.sql</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(modify)\s+(attribute)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(create(\s+or\s+replace)?(\s+force)?|update|delete|insert|set|alter|select|drop|commit|call|enable|add|modify)\b</string>
			<key>name</key>
			<string>keyword.control.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(from|where|(?:order|group)\s+by|having|into|values|distinct)\b</string>
			<key>name</key>
			<string>keyword.other.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(as|of|on|in|is|and|or|not|like|asc|desc)\b</string>
			<key>name</key>
			<string>keyword.operator.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|\|</string>
			<key>name</key>
			<string>keyword.operator.concat.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b((full|left|right)\s+)?((inner|outer)\s+)?join\b</string>
			<key>name</key>
			<string>keyword.operator.join.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(begin|end|return|if|then|for|loop|exception|raise|when(\s+others)?|then|exit\s+when)\b</string>
			<key>name</key>
			<string>keyword.other.udf.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(date|timestamp|[bc]lob|number|float|varchar)\b</string>
			<key>name</key>
			<string>storage.type.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(table|sequence|procedure|view|(unique\s+)?index|trigger|function|cursor|(primary|foreign)\s+key|constraint)\b</string>
			<key>name</key>
			<string>storage.type.modifier.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(count|upper|sum|max|min)(?=\()\b</string>
			<key>name</key>
			<string>support.function.sql</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#oracle</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sql-plus</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--.*$</string>
					<key>name</key>
					<string>comment.line.double-dash.sql</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sql</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.sql</string>
				</dict>
			</array>
		</dict>
		<key>oracle</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(sysdate|systimestamp|decode|to_char|nvl|substr)\b</string>
					<key>name</key>
					<string>support.function.oracle.sql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(dual)\b</string>
					<key>name</key>
					<string>support.class.oracle.sql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(n?varchar2|n?char|varray|object)\b</string>
					<key>name</key>
					<string>storage.type.oracle.sql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(byte|var)\b</string>
					<key>name</key>
					<string>storage.type.modifier.oracle.sql</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.commit.oracle.sql</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(/)(?:\s+|$)</string>
				</dict>
			</array>
		</dict>
		<key>sql-plus</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.oracle.sql</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sql</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(prompt)\s+(.*)$</string>
					<key>name</key>
					<string>meta.sql-plus.prompt.oracle.sql</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(column)\s+(\w+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.oracle.sql</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.column.oracle.sql</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.sql-plus.column.oracle.sql</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.oracle.sql</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.language.oracle.sql</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i)\b(format)\s+(.+?)\b</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.oracle.sql</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>string.quoted.oracle.sql</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i)\b(heading)\s+('.+?')\s?</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)\bjustify(\s+left|center|right)\b</string>
							<key>name</key>
							<string>keyword.other.oracle.sql</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(repheader)\s+(?=off|col|skip|'.*?')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.oracle.sql</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.sql-plus.repheader.oracle.sql</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(off)</string>
							<key>name</key>
							<string>keyword.other.oracle.sql</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.oracle.sql</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.oracle.sql</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(skip|col)\s+(\d+)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>string.quoted.double.sql</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.sql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'.*?'</string>
					<key>name</key>
					<string>string.quoted.single.sql</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.sql</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sql</string>
	<key>uuid</key>
	<string>5A7EB7C0-E6BD-4A8A-A6C0-CDE3D1172900</string>
</dict>
</plist>
