# [PackageDev] target_format: plist, ext: tmPreferences
scope: source.sql
settings:
  increaseIndentPattern: ^\s*(select|into|from|where|(order|group) by|begin|.*\()\s*$
  decreaseIndentPattern: ^\s*(from|into|where|(order|group) by|end;?|\))\s*$
  shellVariables:
  - name: TM_COMMENT_START
    value: '-- '
  - name: TM_COMMENT_START_2
    value: '/* '
  - name: TM_COMMENT_END_2
    value: ' */'
