#!/usr/bin/env bash

set -eu

case $(uname -s) in
  'Darwin') INSTALL_PATH='/Applications/Sublime Text.app/Contents/MacOS';;
  'Linux')  INSTALL_PATH='/opt/sublime_text_3';;
esac

if [[ ! -d ${INSTALL_PATH} ]]; then
  INSTALL_PATH=$(dirname "$0")/../../../..
fi

PACKAGES_DIRECTORY=$(cd "${INSTALL_PATH}" && pwd)/Packages

TEMP_DIRECTORY='/tmp/sublemon-packages'
rm -rf "$TEMP_DIRECTORY" && mkdir "$TEMP_DIRECTORY"
pushd "$TEMP_DIRECTORY" > /dev/null

cp "$PACKAGES_DIRECTORY"/*.sublime-package .

for package in *.sublime-package; do
  dir="${package%%.sublime-package}"

  echo "Processing $(tput setaf 3)${dir}$(tput sgr0).sublime-package"

  unzip -q "${package}" -d "${dir}"
  rm "${package}"
  pushd "${dir}" > /dev/null

  find . -name '*.sublime-snippet' -exec rm -f {} +
  find . -name '*.sublime-completions' -exec rm -f {} +

  case "${dir}" in
    'Java'|'Python') rm -f -- *.sublime-build;;
  esac

  zip -rq "../${package}" -- *

  popd > /dev/null
done

cp -- *.sublime-package "$PACKAGES_DIRECTORY"
popd > /dev/null

rm -rf "${TEMP_DIRECTORY}"
