#!/usr/bin/env bash

set -e

PYTHON_BINARY=python
if which python3 2>&1 > /dev/null; then
    PYTHON_BINARY=python3
fi

publish() {
  dir=$(dirname "$1")
  script=$(basename "$1")

  pushd "${dir}" > /dev/null
  echo -e "Running $(tput setaf 3)${script}$(tput sgr0) in $(tput setaf 2)$PWD$(tput sgr0)\n"
  $PYTHON_BINARY "${script}"
  echo
  popd > /dev/null
}

root=$(dirname "$0")
pushd "${root}/.." > /dev/null

find . -type d -name '.generated*' -exec rm -rf {} +

for snippets in $(find . -name '*.snippets.py'); do
  publish "${snippets}"
done

publish "settings/settings.py"
publish "disco/disco.py"

popd > /dev/null
