<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>css</string>
	</array>
	<key>name</key>
	<string>CSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#css</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>/\*.*?\*/</string>
					<key>name</key>
					<string>comment.block.css</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.css</string>
				</dict>
			</array>
		</dict>
		<key>css</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rules</string>
				</dict>
			</array>
		</dict>
		<key>properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([\w-]+)\s*:\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.key</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.property.value.css</string>
					<key>end</key>
					<string>\s*;</string>
					<key>name</key>
					<string>meta.property.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>!important</string>
							<key>name</key>
							<string>keyword.other.important.css</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.css</string>
								</dict>
							</dict>
							<key>match</key>
							<string>-?\d+(?:\.\d+)?(%|px|em|s)?</string>
							<key>name</key>
							<string>constant.numeric.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(rgba?)\b</string>
							<key>name</key>
							<string>support.function.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[\w-]+</string>
							<key>name</key>
							<string>support.constant.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>".*?"</string>
							<key>name</key>
							<string>string.quoted.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>rules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[\w#@.-])</string>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.rule.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?=[\w#@.-])</string>
							<key>end</key>
							<string>(?=\s*{)</string>
							<key>name</key>
							<string>meta.selector.css</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#selectors</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>contentName</key>
							<string>meta.rule.body.css</string>
							<key>end</key>
							<string>(?=})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#properties</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#css</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>selectors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\w-]+</string>
					<key>name</key>
					<string>entity.name.tag.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#[\w-]+</string>
					<key>name</key>
					<string>entity.name.id.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.[\w-]+</string>
					<key>name</key>
					<string>entity.name.class.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:[\w-]+</string>
					<key>name</key>
					<string>keyword.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@[\w-]+</string>
					<key>name</key>
					<string>keyword.css</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.css</string>
	<key>uuid</key>
	<string>ACA87C3F-31D8-4E5D-B778-4146BBF831F3</string>
</dict>
</plist>
