<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yaml</string>
		<string>yml</string>
	</array>
	<key>name</key>
	<string>YAML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(?=# \[PackageDev\])</string>
			<key>end</key>
			<string>^(?!x)x</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#package-dev</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#yaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=.)</string>
			<key>end</key>
			<string>^(?!x)x</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#yaml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:^|(?&lt;=\s))#.*$</string>
					<key>name</key>
					<string>comment.line.number-sign.yaml</string>
				</dict>
			</array>
		</dict>
		<key>escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[0abtnvfre"/\\N_LP ]</string>
					<key>name</key>
					<string>constant.character.escape.yaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\(x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8})</string>
					<key>name</key>
					<string>constant.character.escape.unicode.yaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.escape.yaml</string>
				</dict>
			</array>
		</dict>
		<key>flow-yaml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.flow.yaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.section.flow.yaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#flow-yaml-internals</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.flow.yaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>meta.section.flow.yaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#flow-yaml-internals</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>flow-yaml-internals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#flow-yaml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scalars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.yaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([^\,\]\}\s].*?)\s*(?=[\,\]\}]|\s#|$)</string>
				</dict>
			</array>
		</dict>
		<key>keys</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=".+?":\s)</string>
					<key>end</key>
					<string>\s*(:)\s</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.mapping.yaml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.key.yaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.yaml</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>entity.name.key.yaml</string>
							<key>end</key>
							<string>"</string>
							<key>name</key>
							<string>string.quoted.double.yaml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escapes</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.yaml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.key.yaml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.mapping.yaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>('(.+?)')\s*(:)(?:\s|$)</string>
					<key>name</key>
					<string>meta.key.yaml</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.key.yaml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.mapping.yaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([^\s'"].+?)\s*(:)(?:\s|$)</string>
					<key>name</key>
					<string>meta.key.yaml</string>
				</dict>
			</array>
		</dict>
		<key>numbers-and-constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(0x[0-9a-fA-F]+|0o[0-7]+|[-+]?[0-9]+|[-+]?(\.[0-9]+|[0-9]+(\.[0-9]*)?)([eE][-+]?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.yaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([Tt]rue|TRUE|[Ff]alse|FALSE|[Nn]ull|NULL|\.nan|\.N[Aa]N|[-+]?\.([Ii]nf|INF))\b</string>
					<key>name</key>
					<string>constant.language.yaml</string>
				</dict>
			</array>
		</dict>
		<key>package-dev</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\bname: )</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.match-group.yaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#yaml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(match|begin|end|\w*(?:Pattern|Match|Marker)|symbolTransformation|cancelCompletion)(:)\s+([&gt;\|]-?)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.key.yaml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.mapping.yaml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.yaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=.)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^(\s+)</string>
							<key>contentName</key>
							<string>source.regexp.yaml</string>
							<key>end</key>
							<string>^(?:\s*(- )|(?!\1).)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.yaml</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.regexp</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(match|begin|end|\w*(?:Pattern|Match|Marker)|symbolTransformation|cancelCompletion)(:)\s+(['"])?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.key.yaml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.mapping.yaml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.yaml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.regexp.yaml</string>
					<key>end</key>
					<string>(['\"])?\s*(?=\s#|$)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.yaml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\$self</string>
					<key>name</key>
					<string>constant.language.yaml</string>
				</dict>
			</array>
		</dict>
		<key>quoted-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.yaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(').*(')</string>
					<key>name</key>
					<string>string.quoted.single.yaml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.yaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.yaml</string>
				</dict>
			</array>
		</dict>
		<key>scalars</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quoted-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers-and-constants</string>
				</dict>
			</array>
		</dict>
		<key>yaml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flow-yaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(---|\.{3})</string>
					<key>name</key>
					<string>keyword.operator.yaml</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.yaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-) </string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.yaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:^|(?&lt;=\s))([&gt;\|]-?)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scalars</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.yaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\S.*?)\s*(?=\s#|$)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.yaml</string>
	<key>uuid</key>
	<string>2BDCCC99-FE27-4B30-9923-32D39B01C5CA</string>
</dict>
</plist>
